### ISSUE TITLE
Incorrectly cut image snippets

### ISSUE THREAD

**Issue by fattynoparents** [knaw-huc/loghi#37]
I'm trying to use another segmentation engine with Loghi, and I noticed that in some cases the MinionCutFromImageBasedOnPageXMLNew minion doesn't cut images well. For example, I have the following image:
![image](https://github.com/user-attachments/assets/fed06309-e58a-4b54-b2e0-f8e81f9f451f)
With the following PageXML file I get correctly cut out snippets, see below:
```
 <Page imageFilename="9882.jpg" imageWidth="2531" imageHeight="3099">
    <TextRegion id="d18362b7-c3d6-48c7-9697-f448e07c0924">
      <Coords points="0,0 2530,0 2530,3098 0,3098"/>
      <TextLine id="line_55d1803a-b200-44ee-9122-7a01c1d2c53c">
        <Coords points="773,306 791,294 967,290 1665,290 1673,282 1961,282 1961,405 773,405"/>
        <Baseline points="834,371 884,368 1134,368 1334,373 1484,368 1634,370 1734,370 1834,374 1901,375"/>
        <TextStyle/>
      </TextLine>
      <TextLine id="c249446d-c43b-4ee5-82c1-3d3d710f3260">
        <Coords points="719,450 1644,450 1644,573 719,573"/>
        <Baseline points="780,545 830,543 930,546 1280,543 1530,545 1580,542 1584,543"/>
        <TextStyle/>
      </TextLine>
    </TextRegion>
  </Page>
```
snippet 1:
![1](https://github.com/user-attachments/assets/b411952f-bc9c-49c3-b84e-430e28957f18)
snippet 2:
![2](https://github.com/user-attachments/assets/65828d24-367e-4b0d-b8c4-bb652b725652)

While with this PageXML file I get totally incorrect snippets, like this:
```
 <Page imageFilename="9882.jpg" imageWidth="2531" imageHeight="3099">
    <TextRegion id="eSc_dummyblock_">
      <Coords points="0,0 2530,0 2530,3098 0,3098"/>
      <TextLine id="line_75cd4332-6d70-488f-a5a1-dee0c2acd88c" custom="structure {type:default;}">
        <Coords points="828,380 1911,383 1914,377 1868,337 1711,315 1709,315 1664,323 1504,313 1503,313 1501,313 1499,313 1487,323 1386,313 1384,313 1382,313 1380,313 1360,332 1298,332 1279,315 1277,315 1275,315 1274,315 1272,315 1246,328 1219,315 1217,315 1215,315 1213,315 1212,315 1198,327 1186,315 1186,313 1184,313 1182,313 1181,313 1179,313 1146,323 1113,313 1112,313 1110,313 1108,313 1107,313 1107,315 1095,323 1086,315 1084,315 1082,315 1081,315 1003,323 986,309 986,308 984,308 983,308 981,308 979,308 946,323 922,313 921,313 919,313 917,313 869,328 829,366 828,380"/>
        <Baseline points="829,366 1914,377"/>
      </TextLine>
      <TextLine id="line_820ec823-aab1-4359-aea1-d003f0743877" custom="structure {type:default;}">
        <Coords points="771,550 931,559 933,559 1589,544 1589,538 1573,506 1539,506 1520,488 1518,488 1516,488 1515,488 1513,488 1478,497 1356,490 1355,490 1353,490 1351,490 1336,501 1265,487 1263,487 1262,487 1260,487 1260,488 1258,488 1251,497 1189,488 1188,488 1186,488 1184,488 1167,502 1058,490 1057,490 1055,490 1053,490 1053,492 1034,509 1000,490 998,490 938,490 936,490 934,490 933,490 905,511 879,502 878,502 876,502 821,513 771,547 771,550"/>
        <Baseline points="771,547 1589,538"/>
      </TextLine>
    </TextRegion>
  </Page>
```
snippet 1:
![3](https://github.com/user-attachments/assets/415bf1b0-4a43-4dcf-b5ef-c236b17dbfcf)
snippet 2: 
![4](https://github.com/user-attachments/assets/c19c32f0-1785-463d-addf-42c726e5f45b)

This influences further HTR process a lot and it becomes completely wrong.

Why can this happen? What is so different in these two PageXML files? Can it be that the latter file Coords attrbute has too many points?
Thanks a lot in advance.

**Comment by rvankoert** [comment]
I'm investigating. It is strange. The cause is wrong calculation of the x-height, which results in bounding boxes that have too much height. But i'm unsure what causes that. I will need to look a bit deeper into this issue. It's not the first and last coordinates that are the same.

**Comment by rvankoert** [comment]
Ok, found the cause: the xheight is based on the interline distance and a projection profile. The interline distance was calculated by comparing points of the various baselines. This did not take into account the case where points of the baseline of are above each other. In your case 1 they are fairly above each other. In the second case they are not above each other resulting in longer distances. I fixed it, but have to check some more things including the computational effects of the fix. 
Additionally: if you want to use your own textline contours: add 
-no_text_line_contour_recalculation
in your call to MinionCutFromImageBasedOnPageXMLNew. Otherwise they get recalculated. I'll report back once it is released. Most likely this will be early next week.

**Comment by fattynoparents** [comment]
Ok great, thanks a lot! I will wait for the fix then.

**Comment by fattynoparents** [comment]
Hi, any news about this issue? Is it possible to fix somehow?

**Comment by rvankoert** [comment]
Sorry, some other things took priority. I'm doing a release right now. Thanks for the reminder. If all goes well the release should be available in a couple of hours.

**Comment by rvankoert** [comment]
I released version 2.1.5 with the fixes. I'll write the release notes tomorrow, but you can start using it of course.

**Comment by fattynoparents** [comment]
Thanks a lot! Will try it out in the nearest days.

**Comment by fattynoparents** [comment]
Hi again, I have now checked the new 2.1.5 version, and in some cases it really did help to fix my issue (particularly in the issue that I described above). However, I come across other images that still have the same problem. I can't see much difference between image snippets cut by Loghi after segmentation in Laypa and in Kraken, but I still get awfully different results in transcription, please see below.

Laypa:
![laypa](https://github.com/user-attachments/assets/9a878e38-dbde-43ab-b876-de616f47031f)
Kraken:
![kraken](https://github.com/user-attachments/assets/33a92e66-5a79-46c1-9d95-8dcedca87253)

Here are the image snippets for the last line that looks mostly incorrect.
Laypa:
![365338-df17c933-446d-46c0-bac5-8b2591d88883](https://github.com/user-attachments/assets/c51b1250-d4e1-4a84-9e0b-9ea1b39d3748)
Kraken:
![365338-fb737c58-117e-4797-b672-b7ce3de4371c](https://github.com/user-attachments/assets/d8db1ecf-1c42-4dfe-8453-60c7f5109b2f)

And the XML files.
Laypa:
```
  <Page imageFilename="365338.jpg" imageWidth="2575" imageHeight="3124">
    <TextRegion id="region_56c0df7b-a3b4-4272-8122-a1ffb697fc21">
      <Coords points="0,0 2574,0 2574,3123 0,3123"/>
      <TextLine id="f6901fbf-b481-461c-a968-195d99473507">
        <Coords points="1105,17 1379,17 1379,148 1105,150"/>
        <Baseline points="1170,141 1220,132 1270,121 1315,116"/>
        <TextStyle/>
      </TextLine>
      <TextLine id="c630f4e3-81a3-4fe0-bab0-09202339b4ad">
        <Coords points="721,250 1837,250 1837,381 721,381"/>
        <Baseline points="786,341 886,337 1186,337 1236,335 1436,340 1486,345 1536,347 1636,342 1686,342 1773,349"/>
        <TextStyle/>
      </TextLine>
      <TextLine id="line_26b08871-bc9d-4dbe-a4b0-c61526c696f9">
        <Coords points="313,374 387,374 623,610 1059,611 1059,742 483,742 392,829 313,829"/>
        <Baseline points="378,713 528,710 828,716 978,709 995,710"/>
        <TextStyle/>
      </TextLine>
    </TextRegion>
  </Page>
```

Kraken:
```
<Page imageFilename="365338.jpg" imageWidth="2575" imageHeight="3124">
    <TextRegion id="region_2b593fcf-d4d2-4cd0-aef3-ae5aa123cfed" custom="structure {type:Sidnummer;}">
      <Coords points="1166,27 1338,41 1345,144 1139,157 1132,48 1166,27"/>
      <TextLine id="line_57f74838-94e7-418a-b82a-5c0dffa0c940" custom="structure {type:default;}">
        <Coords points="1260,0 1236,26 1199,8 1210,126 1211,137 1269,140 1271,140 1272,140 1274,140 1274,138 1291,121 1290,112 1264,0 1260,0"/>
        <Baseline points="1210,126 1290,112"/>
      </TextLine>
    </TextRegion>
    <TextRegion id="f2a0a2ab-13cf-4824-9a7b-e1045f6ba4ff" custom="structure {type:Författare;}">
      <Coords points="805,249 1755,249 1790,277 1790,359 1720,387 763,366 770,277 805,249"/>
      <TextLine id="ca1a4c13-1d0f-414f-ab89-f435f5571866" custom="structure {type:default;}">
        <Coords points="793,348 795,350 796,350 796,352 798,352 800,352 939,354 941,354 1041,341 1342,343 1364,359 1366,359 1368,359 1369,359 1465,347 1479,359 1479,360 1481,360 1482,360 1484,362 1550,362 1550,360 1552,360 1578,348 1684,348 1694,359 1696,359 1698,359 1699,359 1757,348 1758,345 1729,310 1673,310 1653,289 1653,288 1651,288 1649,288 1620,286 1618,286 1616,286 1614,286 1585,308 1543,308 1521,289 1519,289 1517,289 1515,289 1514,289 1472,300 1451,284 1449,284 1448,284 1425,284 1423,284 1422,284 1420,284 1420,286 1406,300 1375,288 1373,288 1371,288 1369,288 1368,288 1350,303 1331,284 1331,282 1330,282 1328,282 1326,282 1324,282 1323,282 1291,301 1253,288 1251,288 1250,288 1248,288 1246,288 1225,301 1206,282 1206,281 1205,281 1203,281 1201,281 1199,281 1163,296 1130,288 1128,288 1126,288 1125,288 1123,288 1123,289 1111,300 1085,282 1083,282 1081,282 1080,282 1078,282 1041,300 1022,281 1022,279 1020,279 1019,279 1017,279 927,298 906,279 906,277 904,277 902,277 901,277 899,277 857,300 821,300 795,333 793,348"/>
        <Baseline points="795,333 1758,345"/>
      </TextLine>
    </TextRegion>
    <TextRegion id="region_47309fad-c7bc-4239-b5f0-5ea6a34bed3a" custom="structure {type:Sehänvisning;}">
      <Coords points="388,603 2123,603 2186,617 2193,713 2179,754 368,761 361,666 388,603"/>
      <TextLine id="line_3f6448de-15b4-4c2d-a6e7-149d607ac681" custom="structure {type:default;}">
        <Coords points="383,704 381,756 454,756 454,754 456,754 458,754 458,753 482,730 795,732 796,732 864,716 953,720 954,720 994,709 996,706 993,697 383,695 383,704"/>
        <Baseline points="383,704 755,713 996,706"/>
      </TextLine>
    </TextRegion>
  </Page>
```

Do you possibly have any ideas why the issue can still persist? Can it be due to the polygons intersection in the second case?
So far the issue happens only on typed pages, haven't seen it happening on hand-written texts.
Thanks again for your help.

**Comment by rvankoert** [comment]
Well the reason is that the determination of the xheight is wrong. Xheight is determined by looking at two things:
- project profile, this should in general be correct, but can off by quite a bit
- by looking at the mask, which is in turn determined by the interline distance
The mask is definitely off in your case, which probably causes the errors. The interline distance seems to be the cause here. The mean from both methods is taken as the final result for xheight. Xheight is then used to determine the number of pixels above and below the baseline that should be included.

There is a workaround: there is the -xheight option you could use. That fixes the xheight to a number you provide. 
In general I'd rather fix this completely, but it is a chicken and egg problem. I can make the current methods optional, so the mask can be ignored in the calculations. That would be an improvement anyway.
